cloudbuild-dev.yaml
**[Issue:](https://app.clickup.com/t/8685pun8e)**
- CloudBuild was crashing due to old yaml file.
**Solution:**
- Updated the yaml file for the GCP.
**Build ScreenShot:**
=> 8685pun8e updated yaml for sandbox

cloudbuild-dev.yaml, cloudbuild.yaml, localcontexts/settings.py
**[Issue:](https://app.clickup.com/t/8685wtqd0)**
- There was no stage to run migrations on both staging and sandbox. Also, Django ORM was unable to connect to the Cloud SQL Instance
**Solution:**
- Install cloud proxy and run migrations using the build script
- Update the host string for Django ORM to successfully connect after deployment
**Build ScreenShot:**
- Before
- After
=> 8685wtqd0 update build to runmigrations and connect Django ORM using unix socket

localcontexts/static/javascript/main.js, localcontexts/static/json/LabelTranslations.json, templates/communities/customize-label.html, templates/partials/_add-translation.html
**[Issue:](https://app.clickup.com/t/8685r2g00)**
-  This feature is requested by Corrie 
*Feature Name:*  Load Label template text translations 
Description: If a community selects Māori, French, or Spanish (the languages that have approved LC translations) as the Label language, it would be really cool to auto-load the translated Label template text in that language. This would help communities working in those languages more easily use the template text, rather than going to our website to copy the translations or not knowing those translations exist. 
**Solution:**
- Created LabelTranslation files and customized the _customize-label_ page using JS.
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/6bb81891-c874-4081-bdfb-149ceaae78b5
=> Added label translations on customized label page

cloudbuild-dev.yaml, helpers/management/commands/run_data_backup.py, requirements.txt, run.sh
Since we'll use Google Cloud to schedule jobs to run `manage.py run_data_backup`. We no longer need to run the data backup command in the run.sh right before running the `manage.py runserver` command.
=> 8685ck3u5 remove code to run backups in run.sh

templates/partials/footers/_auth-footer.html
**[Issue:](https://app.clickup.com/t/8686p45we)**
- Description: Newsletter subscription is only available in PROD.
Currently when you click on the newsletter in the footer, it redirects to dashboard.
Remove the newsletter from there OR redirect to actual newsletter in PROD.
**Solution:**
- Removed the newsletter from the footer.
=> remove newsletter from the footer for the sandbox

localcontexts/static/css/main.css, templates/accounts/select-account.html, templates/bclabels/mini-labels.html, templates/bclabels/tiny-labels.html, templates/bclabels/which-label.html, templates/communities/apply-labels.html, templates/communities/customize-label.html, templates/communities/select-label.html, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html, templates/public.html, templates/snippets/project_notices.html, templates/tklabels/mini-labels.html, templates/tklabels/tiny-labels.html, templates/tklabels/which-label.html
**[Issue:](https://app.clickup.com/t/8685v3xkd)**
- Description: Prevent others from downloading the icons from project pages instead of getting them from the api or project download.
**Solution:**
- Added pointer event none (css proporty) to labels/notices images.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/70b133f8-ea1f-439b-8e06-cf98b47a9732
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/3edf0cb7-0f2d-42ca-a657-df305b673cde
=> Added pointer-event none to labels/notices img's

institutions/views.py, researchers/views.py
**[Issue:](https://app.clickup.com/t/8686qqbhc)**
- Description: Ashley tried to notify 2 communities of a Project and it only notified one and reported the bug on projects/action page. 
- Expected behavior:  All selected communities should be notified.
**Solution:**
- Removed the bug by setting the flow of for loop.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/4d33d29b-6442-4256-832b-96ccb269da5f
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/37c1e1db-6c1a-4e8c-b201-9dd108f5d426
=> 8686qqbhc bug notify multiple communities

accounts/urls.py
**[Issue:](https://app.clickup.com/t/8686u8crr)**
- Description: Several users in the production hub have tried to reset their password using the Forgot Password flow and then not be able to login with the new password or the old password. Most of the users didn't receive the forget Password email with the link to change passwod.
**Solution:**
- Removed the bug by updating the url for ResetPasswordView.
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/443f6ae8-4268-49d2-9863-ed31abb003a5
=> 8686u8crr updated the url of PasswordResetView

localcontexts/static/css/main.css, localcontexts/static/javascript/main.js, templates/accounts/dashboard.html, templates/partials/infocards/_community-card.html, templates/partials/infocards/_community-dashcard.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_institution-dashcard.html, templates/partials/infocards/_researcher-card.html, templates/partials/infocards/_researcher-dashcard.html, templates/partials/infocards/_user-dashcard.html, templates/snippets/notifications.html
**[Issue:](https://app.clickup.com/t/8686g6j1c)**
- Description: There should be some indicator on the dasboard of any accounts that have notifications or how many notifications are in the account. Since the dashboard only shows notifications for the user's account, there is no way of knowing if an institution or community account the user is a part of has notifications pending unless the go into the account and look at the notification icon.
**Solution:**
- Added notification snippet to the dashboard's every card.
- Provided scope for notification snippet to get the notification of individual card.
- Handle notification for individual card and their read and unread status.
- Added settings button to respective account card.
**Before:**
**After:** …
=> 8686g6j1c notification indicator

templates/accounts/select-account.html, templates/communities/apply-labels.html, templates/communities/select-label.html, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/partials/_project-contributor-view.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html, templates/public.html, templates/snippets/pdfs/community-labels.html, templates/snippets/pdfs/project-pdf.html, templates/snippets/project_notices.html
**[Issue:](https://app.clickup.com/t/8685tnmg0)**
- Description: An error was found in one of the templates. Not sure if this is the only place this is set.
Template: localcontexts_db\templates\partials\_project-actions.html - line 266
```
<div class="margin-top-16">
</div>
```
Issue: alt text is set as for a TK notice but the image might be any of the disclosure notices. The before pics are from select-label page.
**Solution:**
Added Alt text for all image tag with src of notice's or label's and handled the alt text in the template.
**Before:**
**After:**
=> 8685tnmg0 alt text for notices and labels

communities/forms.py, institutions/forms.py, templates/accounts/update-profile.html, templates/partials/_update-account.html, templates/partials/infocards/_researcher-card.html, templates/settings-base.html
**Issues:**
- The contact name/email in community/institution account settings is the contact for confirming the accounts, not to contact the account itself.
- UI needed to be updated to be more in line with what we have in Figma.
- When creating a researcher, then going to the dashboard, an error was thrown because of a malformed template tag.
**Before:**
**Solution:**
- Removed the inputs for contact name/email from forms.py and the templates, updated the settings UI
- Fixed malformed template tag error.
**After:**
=> 86873unfh-remove-account-contact-name

templates/partials/infocards/_community-card.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html
**[Issue:](https://app.clickup.com/t/86874wgv4)**
- Description: Going to the Registry, View Public Page buttons UI looks off. For the registry, we should not be able to see the notifications for other accounts, nor their settings. Only the View Public Page should be visible.
**Solution:**
- Updated the HTML to solve the UI bug
**Before:**
**After:**
=> 86874wgv4 Resolved Registry UI bug

accounts/views.py, communities/views.py, helpers/emails.py, institutions/views.py, researchers/views.py, templates/partials/_members.html, templates/partials/_update-account.html, templates/public.html
Basic idea is to eventually move the sandbox into more of a demo hub and disable email sending to avoid user confusion.
**Includes:** 
- Task [8686zykfm](https://app.clickup.com/t/8686zykfm) for disabling sandbox emails. (Modified `emails.py`).
- Task [86874v5y5](https://app.clickup.com/t/86874v5y5) disabling the Contact Us functionality on public pages for the sandbox environment only.
**Before:**
**After:**
- Non-hub user invitation functionality in sandbox environment only (no CU task associated with this).
**Before:**
**After:** 
- Researcher contact info removed from settings for sandbox environment only.
**Before:**
**After:**
=> 8686zykfm disable sandbox emails and 86874v5y5 disable Contact Us on public account pages

templates/communities/edit-label.html, templates/communities/view-label.html
**[Issue:](https://app.clickup.com/t/868735yar)**
- Description: Right now you can see the audio file when you edit the Label and when you first click on a customized Label. When you go to View Label page, the audio player does not appear anywhere, although it should. Also the edit label was not working for tklabel.
**Solution:**
- Updated the HTML to solve the UI bug.
- Updated the logic to avoid error on edit label page.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/f7ecc21d-7d1a-4a31-801a-b747850e761d
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/c38bbe3c-4d80-4bbb-9337-955f2c1270d5
=> 868735yar Resolved Bug for the labels audiofile

accounts/forms.py, accounts/urls.py, accounts/views.py, helpers/emails.py, templates/accounts/password-reset-sent.html
**[Issue:](https://app.clickup.com/t/86877rf1r)**
- Description: If possible, update the support email link UI to match the rest of the links in the Hub. Also, have password reset email match other email templates (reset link put as a button, header, footer, etc.).
**Solution:**
- Added an email template named password_reset template in mailgun.
- Added a custom view for password-reset and used mailgun email function to send email.
- Updated the email support link to match the rest of the links in the Hub.
**Before:**
**After:**
=> 86877rf1r Reset Password link and email UI

communities/views.py, helpers/downloads.py, helpers/utils.py, localcontexts/static/json/Labels.json, templates/accounts/select-account.html, templates/bclabels/mini-labels.html, templates/bclabels/tiny-labels.html, templates/bclabels/which-label.html, templates/communities/apply-labels.html, templates/communities/customize-label.html, templates/communities/select-label.html, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/partials/_project-contributor-view.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html, templates/public.html, templates/snippets/pdfs/community-labels.html, templates/snippets/pdfs/project-pdf.html, templates/snippets/project_notices.html, templates/tklabels/mini-labels.html, templates/tklabels/tiny-labels.html, templates/tklabels/which-label.html
**[Issue:](https://app.clickup.com/t/8685tnmg0)**
- Description: Corrie provided content update for the Labels and Notices img alt text.
**Solution:**
- Updated Alt text for all image tag with src of notice's or label's and handled the alt text in the templates.
- For dynamic assigning of alt text, I inserted the labelAlternateText in the labels.json fetched the alt text from that Json file, and appended it temporarily.
**Before:**
**After:**
=> #8685tnmg0 alt text for notices and labels extended

projects/models.py
**[Issue:](https://app.clickup.com/t/868771r4z)**
- Description: Every time someone runs python manage.py makemigrations a migration file gets created that says the project_privacy  field has been updated when it has not. It creates multiple migrations for the same thing that then gets in the way of other subsequent migrations.
**Solution:**
- The PRIVACY_LEVEL is provided as Set which is unordered in python so changed that to list.
**Before:**
**After:**
=> #868771r4z project_privacy migration error

templates/communities/add-community-boundary.html
Native Land always returns a single boundary. And when multiple boundaries were stored in a single community attribute, the Frontend needed to place that single boundary inside of an array before sending it to the backend.
Since only a single boundary is stored in the boundary attribute, the [ `<single-boundary>` ] is no longer needed
=> #8687a6c16 removed old code from when a single boundary attribute stored multiple boundaries

localcontexts/static/css/main.css, templates/communities/add-community-boundary.html
**[Issue:](https://app.clickup.com/t/86877fkp0)**
- Description: Ashley reported that the "Confirm Location" button on the "Add Community Boundary" page doesn't disable after adding boundaries using NLD, which allows users to press it multiple times and send multiple API calls.
**Solution:**
- Added a spinner icon to the Confirm Location button and disabled it during API call. 
- The Confirm Location button is re-enabled after the API returns the results.
**Before:**
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/545e783f-64e4-4e2d-a2b4-0c7d28988749
=> #86877fkp0 added spinner on Confirm location Button

accounts/views.py, helpers/utils.py, localcontexts/settings.py
**[Issue:](https://app.clickup.com/t/8686qked3)**
- Description: Every few months we accumulate random users with suspicious emails that may or may not be legitimate, so we should set up an email checker on the backend using something like https://rapidapi.com/mr_admin/api/email-verifier to make sure only users with legitimate emails sign up.
**Solution:**
- Added a validation layer on top of registration to validate all the new user's emails. 
- Integrated mail-gun email validation for this purpose.
**Example**
- Before the mail-gun validation process, any email without the email format error(regex) was able to sign up into the hub. But now mail-gun will verify the email and check whether the mailbox for that email actually exist.
=> #8686qked3 Added email verification using mail gun

communities/views.py, notifications/__init__.py, notifications/apps.py, notifications/signals.py
**[Issue:](https://app.clickup.com/t/8687362uf)**
- Description: When a Label is created in a community, the event creates an Action Notification for that community. When I go to delete the Label in the admin panel, the Action Notification remains so when it is clicked on, the notification usually takes the user to the relevant event, in this case, the View Label page. If that Label no longer exists, it throws a 500 error because the Label no longer exists.
**Solution:**
- Added post_delete signal for TKLabels, BCLabels, Projects and JoinRequest models in the ActionNotiofication app.
- Removed the ActionNotification instance deletion loop in views.
- Deleting the ActionNotification based on the instance ID.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/6cc7 …
=> #8687362uf Action Notifications: auto-delete if event instance gets deleted

helpers/apps.py, helpers/scheduler.py, localcontexts/admin.py, localcontexts/settings.py, requirements.txt
**[Issue:](https://app.clickup.com/t/8686qkezr)**
- Description: Set up an auto-delete of new accounts that have never logged in and never verified their emails. There could be instances where someone had deactivated their account after activation but those users should be handled separately. This task is only for those accounts that signed up, never activated and don't have a date for last_login.
**Solution:**
- Added a helper file `scheduler.py` to setup a job that runs at the start of every month and deletes all the inactive users.
- Added django-apsscheduler to schedule jobs.
=> #8686qkezr autodelete inactive accounts

templates/partials/infocards/_community-card.html, templates/partials/infocards/_institution-card.html
**[Issue:](https://app.clickup.com/t/8687azkcp)**
- Description: As an admin for the Southwest Community the settings icon wasn't showing, it only shows at the moment for account creators. Since admins can also access the settings, the icon should show for them too.
**Solution:**
- Updated the rendering condition for settings icon.
**Before:**
**After:**
=> #8687azkcp Add settings option for account cards for all admins

localcontexts/admin.py
Problem:
When user tried to look at the admin panel for HubActivity, was throwing an unbound variable error for some researcher related activity. Was happening because the hub activity for researcher was nested when it tried to assign `account_link`, `account_id` and `account_name`. 
Solved by initializing `account_link`, `account_id` and `account_name` variables in HubActivity admin before they were assigned and passed through to `action_message`.
=> #86878qevr fix HubActivity error in Admin panel

projects/views.py
- Allow Embed page to show even if Hub is in maintenance mode. 
- Allow Project View page to show even if Hub is in maintenance mode.
=> #86875x0x9 Allow Embed and Project page in Maintenance

.github/workflows/run_testcases.yml, pyproject.toml
Introduces test coverage which starts off at 15%. We can incrementally increase it until we've reached our target around the 90% range.
In order to test this PR, you can run...
`pytest --cov=.  --cov-report=term-missing --cov-fail-under=15`
this is what's being run in the run_testcases.yml file
=> #86872uzx7 add test coverage

helpers/utils.py
**[Issue:](https://app.clickup.com/t/8687c89p5)**
- Description: I found a bug while testing our app. When a user accepts a request from community as viewer. Then a key error occurs.
**Solution:**
- Updated the member role in add_user_to_role function.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/aafa12e9-3f9e-4a1b-9ca8-a80fd0f9ccd5
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/efda089b-4462-4fe8-a577-b8cd5254b286
=> #8687c89p5 Correct-member-role

communities/views.py, institutions/views.py
**Problem:** 
Account creation in the sandbox takes user to the preparation step which talks about the account confirmation step. Since the sandbox does not have/need a confirmation step, the preparation step does not need to be there either.
**Solution:** 
Have the preparation step view detect environment, and if it's sandbox, skip directly to create account page.
**Before (institution account creation with preparation step):**
https://github.com/localcontexts/localcontextshub/assets/41635757/cb0691d9-5768-44e2-ba71-7360b66d662e
**After (institution account creation without preparation step):**
https://github.com/localcontexts/localcontextshub/assets/41635757/3bf323a8-fa1b-40c8-8ce6-374ace102c21
Functionality is the same for both community and institution account creation.
=> #86874v7z3 Skip Confirmation Preparation Step in Sandbox

accounts/forms.py, accounts/urls.py, accounts/views.py, helpers/emails.py
**[Issue:](https://app.clickup.com/t/8687c2q86)**
- Description: Don't think we have anything like this but we should have a confirmation email that is sent to users when their email is changed from their profile (like other platforms do).
This email can either be:
- A confirmation email that a user is sent to the original email letting them know that the email is being changed and an email sent to the new email asking to confirm the email by clicking a button. If not clicked, the email doesnt change in the profile.
- A notification email to the original email saying that their email has been changed and if this was done in error to contact us. No confirmation needed, email changed right away.
- A mix of 1 and 2.
**Solution:**
- Added the functionality of detecting email changes on the …
=> #8687c2q86 Added functionality of confirming email change

localcontexts/wsgi.py, notifications/signals.py
**[Issue:](https://app.clickup.com/t/8687fv9bk)**
- Aps scheduler is not running on the develop instance.
- Auto deletion of notification is not working when a label is deleted on the notification instance.
**Solution:**
- Added APS scheduler in the wsgi file
- Updated signal declaration for notifications
=> #8687fv9bk fix-bugs-on-develop

requirements.txt
The purpose of this PR is to resolve this [issue](https://github.com/localcontexts/localcontextshub/security/dependabot/28). I verified that no conflicts were caused by updating the suggested requirement.
=> #8687umtfz dependabot-discovered issue

templates/partials/_update-account.html
Video Demo:
* shows **community** account still views link
* shows **researcher** account does not view link
* shows **institution** account does not view link
https://github.com/localcontexts/localcontextshub/assets/145378945/0fc5a272-ad01-4e48-ba0a-7c487654f189
=> #8687uqu8x remove boundary crud link for non community accounts

communities/views.py, institutions/views.py, researchers/views.py, templates/partials/_project-actions.html
**Problem:** 
When someone would create a Project and add a Project Person's email only, on Project edit that user would get an error because of the way views for Project contributors were set up.
**Solution:** 
Simplified the views to exclude the code that was causing the issue and also added a condition in the Project Action template for handling cases where there either wasn't a name or an email for a Project Person on save.
**How to test this PR:**
- Create a Project and add one Project Person with just email no name, and one with just a name no email. Save Project
- Go to edit this Project and just save it again.
- If there is no error and you still have your Project Person entries the way they were set up originally, then error was fixed.
=> #8687xm41k Project Person error on Project edit fix

communities/views.py, templates/partials/infocards/_community-dashcard.html
How to duplicate bug.
* create a community
* invite another user as admin
* log-in as the invited user > navigate to community settings page > click on "Boundary Community Location" button
* observe 
* the settings button in the top right corner disappears 
* the user's role next to the image on the left disappears
-------------------------------------------------------
**Before Fix**
**After Fix**
=> #8687ypnr4 Resolve Issue With Disappearing Button

helpers/emails.py, helpers/utils.py, researchers/views.py
**[Issue:](https://app.clickup.com/t/8685dweqe)**
- Description: Currently, if a community has been notified of a Project and that Project gets edited, there is no notification that lets the notified community know that anything has changed on the Project. There should be an action notification in the GUI and possibly an email sent as well.
**Solution:**
- Detected the change in the Edit project form.
- Updated the change flag based on the change in notice or notice translations.
- Get communities based of the status is Labels Pending or Acknowledge Notice.
- Sent ActionNotification to notified communities based on whether the change is detected or not.
**Before:**
**After:**
The [link](https://drive.google.com/file/d/1WrK_-uLoaaU3AbEECpGYjb2ily5D5yJq/view?usp=sharing) for video demo.
=> #8685dweqe Notification-for-Notified-Communities

api/base/serializers.py, api/versioned/v2/views.py
**[Issue:](https://app.clickup.com/t/8687wa0f0)**
Create a call for the subscriptions model that uses the date last updated as a param and gets all the items after that date so that SF can pull numbers from that call only for items after a specific date daily or twice daily.
As a user does any action that lower's a subscription count (creates a project, adds an admin/editor, creates an API key, etc., the Date Updated field in Subscriptions model is updated along with the associated count being affected.
When Rohit submits an API Call for subscribed users, the datetime that this call was last run by SF would be added as a parameter.
The Hub will use that datetime as a start datetime to query the Subscriptions model. If any of the datetimes in the Date Updated field are …
=> #8687tx2w0 Added Api call to update Salesforce

communities/views.py
**[Issue:](https://app.clickup.com/t/8687ypkg0)**
Right now if you go to the View Label page after the Label was deleted, it throws a 500 error, but it should be throwing a 404 instead.
**Solution:**
- Added the missing variable 
- Updated the rendering conditions and redirection from page if label not found
**Before:**
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/9b3f566f-cefd-4be1-8b13-b38c394ed0b6
=> #8687ypkg0 View Label: return 404 instead of 500 if Label does not exist

requirements.txt
This updates pillow to resolve a dependabot [discovered](https://github.com/localcontexts/localcontextshub/security/dependabot/34) vulnerability.
Updating this did not require updates to any other packages.
=> dependabot-discovered-vulnerability-fix

bclabels/forms.py, communities/views.py, templates/communities/select-label.html, templates/partials/_add-translation.html, tklabels/forms.py
**[Issue:](https://app.clickup.com/t/8687ypjdr)**
This was a customized Label that was saved with no default text or translations. 
Set up validation where something has to be in the default text field, otherwise it cannot be saved. Additionally, if there is not a lot of text in the text field (its a short default text), the buttons still appear as they should -- to the right of the container (image below).
**Solution:**
- Adjusted the width of the div containing label content.
- Added clean for Customize BCLabels and TKLabels to set up validation on the empty label text field.
- Updated the form call in the view to ensure that the form validation is being properly called. 
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/9f882953-162f-4972-8b …
=> #8687ypjdr Should not be able to save a Label if default text is empty

institutions/utils.py, institutions/views.py, localcontexts/static/css/main.css, templates/partials/_project-actions.html
**[Issue:](https://app.clickup.com/t/8687zam2m)**
Notification count - notification per community notified
When a Project is created, in Project Actions there is an option to Notify Communities.
Count -1 per community added to notification modal.
**Solution:**
- Detected the number of communities notified by the institute and reduced that no from the institute's notification count.
- If the notification count is 0 disable the notifying communities process.
- Showed appropriate messages when the user tries to notify any community while the notification count is 0.
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/96fea805-2dd9-462b-aa2a-8c3b418730ef
=> #8687zam2m Added notification count functionality for subscriptions

localcontexts/static/css/main.css
**[Issue:](https://app.clickup.com/t/86879gwuc)**
Help text should appear underneath the button and should not be transparent.
**Solution:**
- Adjusted the CSS of that div to make it appear under the button and opaque.
**After:**
=> #86879gwuc Download Labels button help text floating away

accounts/views.py
Fixed Projects filtered by Labels in the Project Board were being duplicated if they had more than one Label attached.
Solution: added `.distinct()` to the query
=> #86884w996 Bug: Project Board filter with Labels remove duplication

templates/accounts/member-invitations.html
**[Issue:](https://app.clickup.com/t/86886vqv4)**
When the invite role is admin, the request doesn't show the user its proposed responsibility.
**Solution:**
- Corrected `invite.role` in template.
**Before:**
**After:**
=> #86886vqv4 Corrected admin invite role

localcontexts/static/css/main.css, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/projects/projects.html
**[Issue:](https://app.clickup.com/t/8688bb65t)**
We are going back to our original UI of hover-over information dropdowns for disabled buttons.
From this:
Back to this:
**Solution:**
- Updated the styling of help-text on notices and project disabled buttons
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/9b6e548c-c596-4a43-bdcd-8beb1d60a160
=> #8688bb65t UI Update: Disabled button dropdowns

localcontexts/settings.py
Keep getting the error below for all profile related templates that seems to be an issue with the countries package and Django 5.0 (see StackOverflow discussion and temp fix [here](https://stackoverflow.com/a/77859948))
=> #8688faqx4 Country package issue blocking profile related pages from loading

templates/public.html
When public community has a boundary derived from Native Land Digital, it displays a message and link to: https://native-land.ca/contact
=> #86884f3tq-public-community-nld-annotations

communities/urls.py, templates/partials/_project-actions.html, templates/projects/projects.html
**From an error Ashley had:**
> When you Create a Project by clicking the button on the Researcher page it creates the project under a community account. 
<hr>
**In this PR:**
- Fixed the template link where clicking on Create a Project in a researcher account would take you to creating a community Project instead.
- Renamed the community create Project path name from `create-project` to `community-create-project` to create distinction between where the path will take the user in the templates.
<hr>
**After:**
https://github.com/localcontexts/localcontextshub/assets/41635757/26b616d6-9d3a-4e49-92b9-fff982b8db03
=> #8688jznmy Bug Fix: Researcher create project error

localcontexts/admin.py, templates/admin/dashboard.html
**[Issue:](https://app.clickup.com/t/86880yzda)**
The link to the admin table is broken and giving back 500 error.
**Solution:**
- Updated the link with correct URL.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/ef79fd83-50a9-4f43-abb4-cf4baa1c6976
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/9575e9ea-d819-4be0-af1c-1576f917a9bd
=> #86880yzda Broken Admin Tables link in Admin Dashboard

accounts/views.py, localcontexts/static/css/main.css, templates/accounts/subscription-inquiry.html
**[Issue:](https://app.clickup.com/t/8688h60qg)**
- Remove account type since its not reflected in SF
- Asterisks need to be added to the required fields:
- First name (confirm this)
- Email
- Inquiry Type
For the anon form it should create a lead first, making the organization name optional. If we need to pass something, just pass Unknown.
**Solution:**
- Updated the SubscriptionForm to remove account type in subscription-inquiry view
- Updated the template for subscription-inquiry to include the optional Affiliation's / Organization's form field with the tooltip description of field
- Added asterisk's with the required form fields
- Updated CSS to style the required text as title attribute
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/9f06 …
=> #8688h60qg Anon User Subscription Form Adjustments

accounts/views.py, projects/models.py, projects/utils.py, templates/public.html
**[Issue:](https://app.clickup.com/t/86887gk2m)**
From the latest subscription meeting it was decided that some functionality was to be adjusted for accounts. This specific task relates to institutions only. 
- Public Projects can be viewed and downloaded regardless of subscription status
- Private Projects cannot be downloaded by anyone
- Institution accounts do appear in the registry but their public pages will contain content labelling them as Active (if subscription) and Inactive (if no subscription). Relevant task here: 
- Unsubscribed institutions cannot be added to Projects as contributors.
- Unsubscribed institutions cannot be joined via account creation process or from their public registry page.
**Solution:**
- Updated the Query for Projects on Project-board and …
=> #86887gk2m Adjusted institution account functionality

helpers/views.py, institutions/utils.py, institutions/views.py, researchers/views.py, templates/researchers/projects.html, tests/functional/test_limit_researchers_functionality.py
**[Issue:](https://app.clickup.com/t/8688p5hjk)**
Tested an account where my project count was 0, so the Create Project button was disabled, but when I go directly to create-project (http://localhost:8000/researchers/projects/create-project/1/) I am still able to create a project. This needs to be blocked for Researchers and Institutions.
**Solution:**
- Performs checks on ```create-project/``` URL for institution and  researcher account to stop access of unauthorized users
- Removed unnecessary code to improve code base 
**After:**
**Institution Account:**
https://github.com/localcontexts/localcontextshub/assets/145371882/098a2b22-7e91-4255-bd9c-f49693ecc460
**Researcher Account:**
https://github.com/localcontexts/localcontextshub/assets/145371882/0ccce511-8837-4d7b-8ba5- …
=> #8688p5hjk Block Create Project URL hitting

accounts/decorators.py, accounts/views.py, templates/partials/headers/header-content.html
**[Issue:](https://app.clickup.com/t/8688q2mz6)**
Use case:
User has a profile created but not an account yet but is interested in subscriptions. Maybe this user does not know what kind of account they should create.
The subscription form at /subscribtion-inquiry should be available to logged-in users. Currently it is only available to anon users and if someone who is logged in tries to access that URL, they are redirected to the dashboard.
**Solution:**
- Updated the decorator from ```unauthenticateduser``` to ```zero_account_user```
- Performs check if the user is associated to any institution or researcher account 
- If the association is present the user is redirected to dashboard else continue to ` /subscription-inquiry/ ` URL  
**After:** …
=> #8688q2mz6 allow anonymous subscription form

researchers/views.py
**[Issue:](https://app.clickup.com/t/8688uhct0)**
In prod, I went to edit a project that already had a contributor in it. But when I edited the project, I didnt do anything to the project, just saved the project and this is what showed up:
The contributor section is blank. This might be able to be fixed with  but not sure. I am also not able to delete the non-hub contributor I added.
View of Project when editing it and didnt change anything.
**Solution:**
- Updated the process of deleting contributors from project
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/c4bfada4-02fc-490c-8d8e-11d3236c689e
=> #8688uhct0 Non-User Project Contributor issues

helpers/utils.py
**[Issue:](https://app.clickup.com/t/8688wzakr)**
When I attempted to remove the notice from the project, I encountered an error.
**Solution:**
- Adjusted the loop on deleting notice.
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/09bdf52a-9f2e-4329-a1de-791a827b4136
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/37b72de3-2bfe-45ff-9fac-28a2899b1905
=> #8688wzakr Error when removing notice from project

researchers/views.py
This fixes an issue when deleting a researcher project.
**Before, This Error Occurs**
---------------------
**After, No Error Occurs**
https://github.com/localcontexts/localcontextshub/assets/145378945/ad0de52c-3277-4eb2-a3d9-8c320acc454b
=> #8688pwpcf fix error deleting researcher project

accounts/decorators.py, accounts/utils.py, institutions/utils.py, researchers/views.py
**[Issue:](https://app.clickup.com/t/8688t720h)**
Since the sandbox is a more of a demo space for users to see how the hub works, we need to ensure that subscriptions functionality is completely bypassed / disabled and/or hidden in the sandbox environment so that users can test workflows without needing an active subscription, counts, etc.
There is some functionality across the hub that is already set up for the sandbox (ie. environment-specific content, email sending, download limitation, contacting other accounts, etc.) which can stay as is but we need to make sure that each account can create/edit Projects, add contributors to Projects, be able to customize Labels and add them to Projects (if they are a community), and add/remove members without needing counts or a …
=> #8688t720h subscriptions handling in sandbox

requirements.txt
Certifi 2024.07.04 removes root certificates from "GLOBALTRUST" from the root store. These are in the process of being removed from Mozilla's trust store.
=> Resolved vulnerability discovered by dependabot

accounts/views.py
Added decorator to allow Newsletter subscribe and preferences pages to work even if the hub is in maintenance mode
=> #8687dtbuj Disable Maintenance Mode for Newsletter pages

templates/partials/_project-actions.html
While in discussions with @pbuttigieg on schema.org mappings, he indicated that since the Labels do not have a direct page for people to go to when going to look at the Label itself, it would at least be helpful to have a direct link to the section where the Labels are held so that it takes people directly there. Added to Notices section as well.
**Direct links to sections will look like the following:**
- Project Labels: localcontextshub.org/projects/{UUID}#labels
- Project Notices: localcontextshub.org/projects/{UUID}#notices
=> #8688x1bc3 Added anchor to Project Labels or Notices section

accounts/utils.py, helpers/utils.py, institutions/urls.py, institutions/utils.py, institutions/views.py, localcontexts/static/javascript/main.js, researchers/urls.py, researchers/utils.py, researchers/views.py, templates/register-base.html
**[Issue:](https://app.clickup.com/t/8688wgz4k)**
As discussed in Dev Team meeting on 6.25.24, there are some subscription and inquiry form functions that can be moved to helpers in a subscriptions specific file that helps manage the SF and subscription checks being done in the hub. This will be to reduce code redundancy. Here are some functions found that may need to be looked at:
check_subscription
form_initiation
handle_confirmation_and_subscription
confirm_subscription
institute_account_subscription
subscription_inquiry
If inquiry form specific (i.e sending information to SF or getting information from SF), this should include all 4 account types. If checking subscription model for existing object, this should be for subscriber accounts only (institution & …
=> #8688wgz4k Subscription Code Clean-Up

templates/partials/_project-actions.html
**[Issue:](https://app.clickup.com/t/8687u2kp0)**
When Labels have been applied to a Project, the small caret is hard for folks to see so it needs to be made more prominent.
**Solution:**
- Updated the size of down pointer
**Before:**
**After:**
=> #8687u2kp0 Make caret larger on Labels dropdown on Project Action Page

localcontexts/static/css/dashboard.css, localcontexts/static/css/main.css, templates/partials/infocards/_community-dashcard.html, templates/partials/infocards/_institution-dashcard.html, templates/partials/infocards/_researcher-card.html, templates/partials/infocards/_researcher-dashcard.html
**[Issue:](https://app.clickup.com/t/8687q3kfw)**
Current design in hub 04/03/2024
Actual design in Figma 04/03/2024
**Solution:**
- Updated CSS to decrease width of dashcard text
- Updated HTML to render the required design 
**Before:**
[ui(before).webm](https://github.com/localcontexts/localcontextshub/assets/145371882/a64b79bb-5753-4c54-9c7c-db3f92e464a7)
**After:**
[ui(after).webm](https://github.com/localcontexts/localcontextshub/assets/145371882/2dac33bf-103e-4887-839d-33474a44dbcc)
=> #8687q3kfw Bold and lengthen activity cards on account dashboard

templates/partials/_add-projectperson.html
**[Issue:](https://app.clickup.com/t/8688zhx0f)**
Extra error field showing under contributors section:
**Solution:**
- Updated the conditional statement to check if there is an error present or not. 
**Before:**
https://github.com/localcontexts/localcontextshub/assets/145371882/9b3b5e9a-21dd-4f97-b880-292b9670acb5
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/af9bbdc6-3fd7-4910-9295-ebec5dbd1541
=> #8688uhz5x Removed unnecessary error field from project page

localcontexts/static/css/main.css
**[Issue:](https://app.clickup.com/t/8688zhx0f)**
From HSM 7.2.24: update the spacing of the account name and the subscribed/confirmed/certified checkmark to be 8px instead of the current 14px.
**Solution:**
- Updated CSS to decrease right margin of icon 
**After:**
=> #8688zhx0f Subscribed Check Mark Margin fix

helpers/emails.py, helpers/utils.py
**Issue:**
Failed Subscription report to tech team
The unsuccessful attempt to subscribe is reported to `support@localcontexts.org` in every environment, which is now only limited to PROD
**Solution:**
- Added the conditional statement to filter out PROD environment
=> Updated the email for failed subscription report

localcontexts/static/css/main.css, templates/institutions/connections.html, templates/partials/_notices.html
This changes the width of Notices and Connections so the text takes up more of the blank space.
=> #8688x2vug adjust notices and connections section

templates/institutions/projects.html, templates/researchers/projects.html
**[Issue:](https://app.clickup.com/t/8688zphtr)**
On the Projects page for the researcher and institution accounts, the gap between the subnav and bottom card is greater than if you go to the Notices or Connections pages.
**Solution:**
- Updated the conditional statement to render alerts div
**After:**
- **Institution:**
- **Researcher:**
=> #8688zphtr Subscriptions branch: researcher/institution subnav card gap

templates/partials/_project-actions.html
Fixed bug in which a disabled button was clickable.
There is a [task](https://app.clickup.com/t/86895rbq0) for modifying the BE so project can't be editable even if one bypasses the ui button and visits the page directly
=> #86894v2g3 fixed clickable disabled button

localcontexts/static/javascript/main.js, templates/base.html, templates/partials/_alerts.html
Toastr JS is being used to show the alerts instead of a div
Video Demo:
https://github.com/user-attachments/assets/a4ea7f72-fc29-4390-aa5e-48732b1da7ec
---
Image
----
How to Test
* Add this snippet to the bottom of the `dashboard` View in `accounts/views.py`
```
messages.add_message(
request, messages.INFO,
'SHORT MESSAGE')
messages.add_message(
request, messages.INFO,
'<a> HTML Content Not Rendered </a>')
messages.add_message(
request, messages.INFO,
'profile activation successful. You are now able to login'
)
messages.add_message(
request, messages.INFO ,
'Thank you for your submission, our team will review and be in contact with the subscription contact. You will be notified once your subscription has been processed.'
)
messages.add_message(
request, messages.INFO,
'MEDIUM LONG MESSAGE …
```
=> #8687c885q alert modification

templates/boundary/update-boundary-via-native-land-and-shapefile.html, templates/communities/add-community-boundary.html, templates/communities/update-boundary-via-native-land-and-shapefile.html, templates/partials/_project-actions.html
Below are screenshots for various scenarios:
-------------
A Project with Boundary Derived from NLD
The url navigates to: https://native-land.ca/maps/territories/nansemond-2/
-----
A Project with Boundary Derived from a Shapefile
---
A Project with Boundary and No Name
=> #86891zwnh nld boundary links non json page

researchers/views.py
**[Issue:](https://app.clickup.com/t/86897rv7h)**
It was decided in this [thread](https://localcontexts.slack.com/archives/C05SU5R08R1/p1722452988738389?thread_ts=1722450545.341949&cid=C05SU5R08R1) to update the lead_data for the researcher account for organization_name from First_name to First_name + Last_name.
**Solution:**
- Updated the organization name in form from first name to get_users_name
**After:**
- **Sample lead_data with both first and last name:**
`{'hubId': '9_r', 'companyName': "Sabeen's Cmmounity Account", 'email': 'sabeen.ammar+990@localcontexts.org', 'firstname': "Sabeen's", 'lastName': 'Cmmounity Account', 'oppName': "Sabeen's Cmmounity Account", 'inquiryType': 'subscriber', 'isBusinessTrue': False}`
- **Sample lead_data with only first name:** …
=> #86897rv7h Update lead date for researcher

accounts/forms.py, helpers/utils.py, researchers/views.py, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html, templates/researchers/connect-researcher.html
**[Issue:](https://app.clickup.com/t/8688zphtr)**
Herbert was able to remove both first name and last name from the settings page, which should not have happened as this will create an error in future subscription calls and also the users already present on the HUB may not have a first name and last name and their subscription calls will also generate the same error. The user should not be able to remove the first name and last name from settings as well, Researcher subscription journey should mimic the first name check like institution.
**Solution:**
- Updated UserUpdateForm's field first name to required true
- Updated the `connect-researcher/` page to include UserCreateProfileForm for first and last name
- Optimized the helper function for form initiation
**After:**
- …
=> #86895xw7x researcher name bug

helpers/utils.py, institutions/views.py, researchers/views.py
**Discription:**
When the notices page of the institute and researcher is opened, a variable [error](https://localcontexts.slack.com/files/USLACKBOT/F07FRKFSHT5/13) occurs. This PR is to resolve the backend issues that occurred during the rebasing of "subscription" with "develop" branch.
**Solution:**
- Updated the form_initiation function for the service provider account
- Updated the logic of getting the value of the variable
**Before:**
**After:**
https://github.com/user-attachments/assets/6ca3bf24-998c-4838-baba-392dc2bcf361
=> Resolved variables error of notices page

helpers/utils.py, institutions/views.py, researchers/views.py, templates/partials/_notices.html
**Discription:**
When the notices page of the institution's account is opened, the UI has some bugs, including duplicate Download Notices and Share buttons, and some text that is styled incorrectly.
**Solution:**
- Updated the template to render correct data 
- Updated the view to pass correct value of variable
**Before:**
**After:**
https://github.com/user-attachments/assets/cd4fd736-dbd5-459b-b64e-d849a92e1504
=> Frontend issues

accounts/utils.py, helpers/utils.py, institutions/views.py, researchers/views.py, serviceproviders/views.py, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html, templates/researchers/connect-researcher.html, templates/serviceproviders/create-service-provider.html
**[Issue:](https://app.clickup.com/t/86899db6e)**
Currently, the inquiry type for account creation has extra options that are not necessarily needed.
For this task:
Remove The inquiry type in all account creation forms (Researcher, Institution, Service Provider, Community) but NOT the anonymous user form (this form will work as it is now).
Send the inquiry type automatically to SF based on the kind of account it is.
- Community inquiry type: Membership
- Institution inquiry type: Add 2 radio buttons. Option 1: Subscription. Option 2: Collections Care Notices Only. Then send to SF 
whichever was selected.
- Researcher inquiry type: Subscription 
- Service Provider inquiry type: Service Provider
**Solution:**
- Updated the template for institution and non-ROR institution …
=> #86899db6e Inquiry Type: Account creation form

accounts/utils.py, accounts/views.py
When testing the subscription inquiry, I discovered that communities and non-ror institutions with apostrophes in their names are causing an error, which prevents the SalesForce call from executing.
**Solution:**
- Appended the apostrophe with escaping slash in the data attributes before passing them to Front-end.
- Because of escaping slash the apostrophe sh showed in recommendations correctly
**After:**
=> Fix for subscription inquiry

helpers/forms.py, templates/communities/approve-label.html
**Before**
User selects 'No'
**After**
User selects "No, I do not approve this Label"
=> #8689am8a4 Update Label Approval page UI

templates/partials/_alerts.html
The min height has been updated. Looking at the dev tools inspector, the sum of the height is about 64px:
-------------------------
Here's what it looks like in action:
=> #8687c885q-alert-size-update

accounts/views.py, templates/accounts/deactivate.html
Accounts are displayed for creators and members similar to the accounts page
for creators:
https://github.com/user-attachments/assets/5565ae60-8f05-41f3-b0df-83f794996b4e
---
for members:
----
for non creator and non member
=> #8689bxfry display accounts

templates/communities/connections.html, templates/institutions/connections.html, templates/researchers/connections.html
Previously Researcher cards were not showing location information.
Before:
After:
=> #8689dru4t: Updated Researcher connections card bug

templates/boundary/show-remove-preexisting.html, templates/partials/_update-boundary-main-area.html
This expands the boundary name width to take up the full width when necessary.
**On Project Boundary Page**
----
**On Project Settings Page**
=> #8689ef9md-boundary-name-width

accounts/utils.py, localcontexts/static/css/dashboard.css, serviceproviders/views.py, templates/account_settings_pages/_api-keys.html, templates/accounts/dashboard.html, templates/accounts/member-invitations.html, templates/accounts/preparation.html, templates/accounts/registry.html, templates/accounts/select-account.html, templates/partials/_member-requests.html, templates/partials/_notices.html, templates/projects/projects.html, templates/serviceproviders/create-service-provider.html
- Content updates from doc.
- CU-8689exv4q: updated select account content
- CU-8688wn3rd: Updated Notices content page for SP
- CU-8688wn8m5: Updated Notice error message content
- CU-86890yuz8: no results cards updated
- CU-8688vk435: prep step content updated for SP
- CU-8688vnfvn: Create account content updated
- CU-8688xv8pf: API Key settings content updated
- CU-8688w5419: Minor registry content update
- Small UI changes for "No Results cards" to match across the Hub:
---
=> Misc SP content updates

requirements.txt
This is based on: https://github.com/localcontexts/localcontextshub/security/dependabot/43
=> Updated requirements.txt to resolve openssl vulernability

localcontexts/static/css/main.css, templates/accounts/login.html, templates/accounts/select-account.html, templates/admin/partials/_data-visuals.html, templates/boundary/update-boundary-via-native-land-and-shapefile.html, templates/communities/apply-labels.html, templates/communities/create-community.html, templates/communities/customize-label.html, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html, templates/partials/_add-contributors.html, templates/partials/_add-projectperson.html, templates/partials/_add-translation.html, templates/partials/_alerts.html, templates/partials/_connect-organization.html, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/projects/create-project.html, templates/projects/project-comment.html, templates/projects/project-status.html, templates/public.html, templates/researchers/connect-researcher.html
Make `i` more visible for tooltip markers.
Before:
After:
=> #8689kxnjq: Updated tooltip markers to improve visibility

accounts/decorators.py, serviceproviders/forms.py, serviceproviders/templatetags/custom_service_provider_tags.py, serviceproviders/urls.py, serviceproviders/views.py, templates/account-settings-base.html, templates/account_settings_pages/_preferences.html, templates/account_settings_pages/_update-account.html, templates/accounts/select-account.html, templates/partials/_connections.html, templates/public.html
Misc SP updates based on our discussions
- #8689kbeef: Add content to create account page if users are unsure of which account to create
---
- #8689kbe8d: Move show connections SP setting to preferences page
---
- #8689kbb95: connections section bug in SP public view page
Fixed bug where the connections section was not showing in the card on the public view page when no OTC notices were added:
Before:
After:
---
- #8689k5g0k: uncertified SP connections count error
Fixed bug where an uncertified SP account was not loading due to connections count tag.
---
- #8689k5xfk: Add no results card to connections pages for all accounts when no connections are made.
=> Misc SP Updates

accounts/urls.py, accounts/views.py, communities/views.py, institutions/views.py, templates/snippets/modals/leave-account-modal.html
Issue:
- Going to profile -> accounts and then trying to leave an account, the user would hit a 403 error because the `remove_member` views in `communities/views.py` and `institutions/views.py` at some point got a decorator which only allowed admins of that account to remove members.
Solution:
- Create a `leave_account` view in `accounts/views.py` where the user could remove themselves from an account that they did not create but were just a member of.
=> #8689c0ert Remove User From Account Bug & Refactoring

accounts/urls.py, accounts/views.py, institutions/views.py, localcontexts/static/css/dashboard.css, templates/account-settings-base.html, templates/account_settings_pages/_subscription.html
**[Issue:](https://app.clickup.com/t/8687zzy47)**
This should be only available to main admin of the account
The information on the Subscriptions Settings page should be:
**Subscribed Account:**
- Subscription type: Individual, Small, Medium, Large, CC Notice Only(?)
- Counts of how much of each item is left
- Projects
- Users
- Notifications
- Notices and Labels
- API Keys
- Start and end date of the subscription
- Bundle inquiry
- Select bundle type, then send account id, contact info to which email? (support? subscriptions?)
- Cancellation Inquiry
- Should this be a link to a form or who to email?
- Do we have cancellation information available somewhere to link to?
**Unsubscribed account:**
- some information on subscriptions
- link to webform? (or embed webform?) …
=> #8687zzy47 Added subscription settings page

templates/partials/footers/_auth-footer.html
**[Issue:](https://app.clickup.com/t/86895nwwj)**
Our copyright should be updated from the following:
> Traditional Knowledge (TK) and Biocultural (BC) Labels, Notices and Template Text © 2010 - 2024 Local Contexts. All Rights Reserved.
New text:
> All Labels and Notices Icons and Template Texts © 2010 - 2024 Local Contexts. All Rights Reserved.
**Solution:**
- Updated the auth Footer in the HUB 
- Updated the  email templates on Mailgun
**Before:**
**After:**
=> #86895nwwj Update copyright in Hub footer and email footers

communities/views.py, templates/partials/_project-actions.html
Before:
When a community went to apply Labels to a Project, they would be redirected back to the apply Labels page, which was a bit inconvenient and confusing for users.
After:
After a community applies Labels to a Project, they are redirected to the Project actions page, under the Label header so they can review the Labels they have added to the Project. It also now shows an alert that indicates Labels have been applied.
https://github.com/user-attachments/assets/2cc1b23e-3a38-4444-b871-47f22910c0be
=> #8689u5wnm Redirect back to the Project after Label application

accounts/models.py, accounts/views.py, communities/models.py, institutions/models.py, localcontexts/admin.py, projects/models.py, templates/account_settings_pages/_update-account.html, templates/accounts/member-invitations.html, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html, templates/partials/infocards/_account-dashcard.html, templates/partials/infocards/_community-card.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html, templates/partials/infocards/_user-dashcard.html, templates/public.html, tests/unit/test_accounts_models.py, tests/unit/test_communities_models.py, tests/unit/test_institutions_models.py
In this PR:
- [#868a2c37t](https://app.clickup.com/t/868a2c37t): Showing Project Status table in admin under `Helpers` section.
- [#8689qebva](https://app.clickup.com/t/8689qebva): Removed `Location: None specified` placeholders from dashcards -- `get_location()` now returns `None` instead, no placeholder appears for location if none is added in settings or on account creation.
- Adjusted required and not required fields for account models and forms in the settings.
- Changed `Inquiry Type` to `Subscription Type` field name on account creation.
- Removed some unused imports.
=> Misc adjustments

institutions/urls.py, institutions/views.py, localcontexts/static/javascript/main.js, researchers/urls.py, researchers/views.py, templates/account_settings_pages/_subscription-form.html, templates/account_settings_pages/_subscription.html
**[Issue:](https://app.clickup.com/t/8689ycn7z)**
For accounts that are unsubscribed, they should still be able to access the subscription form from their settings page if they would like to inquire again about a subscription. When clicking on button in either case below, this should lead to the subscription web form. I think the form can prefill with name email and Affiliation/Organization name but allowing the user to edit the name and email in case they have a different contact they'd like to add for the subscription request.
Currently, if Affiliation/Organization is already in the Hub, it redirects the user to join that account. But if the user is brought to this form from that account by clicking the subscription request button, it should still send the request since …
=> #8689ycn7z Update Subscription form for HUB users

localcontexts/static/css/main.css, templates/partials/_project-actions.html, templates/projects/project-overview.html
**[Issue:](https://app.clickup.com/t/86897hg9q)**
Problem: Users are finding it difficult to identify which projects are sub/source projects on the project view page
Solution: Sub Project Icons have been added to sub projects on the project gallery page and project view page
Use the icons way of differentiating sub-Projects only in the Projects Board.
**Solution:**
- Updated `_project-actions` template to include the new meta data field "Level"
- Updated `project-overview` template to include the icon and tooltip for subprojects
- Updated `main.css` to include the added styles
**Before:**
**After:**
=> #86897hg9q Updated UI of sub projects

communities/forms.py
**[Issue:](https://app.clickup.com/t/8689agzvf)**
The message box allows for the user to adjust the size of the message box in the bottom right corner. This should be limited to the width of the modal. The height works well (having the modal height grow with the message box is the expected behavior. The width should be locked at the original width so it doesn't go beyond the modal box.
**Solution:**
- Updated the resizing property of `JoinRequestForm` which translates into join modal message box
**After:**
https://github.com/user-attachments/assets/383b2ced-c99a-43eb-adbc-0302ac641180
=> #8689agzvf UI Fix: Request to Join modal message box

accounts/forms.py
**[Issue:](https://app.clickup.com/t/8689agzvf)**
While working on the UI Fix of the Request to Join Us message modal, I found that the message modal in Contact Us is also resizable and the user can stretch the width of the message box beyond the div.
**Solution:**
- Updated the resizing property of `ContactOrganizationForm` which translates into Contact Us modal message box
**After:**
https://github.com/user-attachments/assets/bf4de47d-107c-4200-bc19-20f8df7eb86c
=> #868acy3kb UI Fix: Contact Us message modal
