cloudbuild.yaml
**[Issue:](https://app.clickup.com/t/8685pup39)**
- No Staging of localcontexts on GCP
**Solution:**
- Created a project local-contexts-hub-staging on GCP
- Created application on App Engine
- Configured the Trigger for continuous deployment
- Updated the yaml file
**Build ScreenShot:**
=> 8685pup39 updated yaml for staging

requirements.txt
Fixes denial of service [vulnerability](https://github.com/biocodellc/localcontexts_db/security/dependabot/30) discovered by dependabot.
In order to update protobuf, google-api-core needed to be updated as well.
=> Resolved DOS vulnerability detected by dependabot

templates/projects/embed-project.html
Testing out new edits for embed template to show in iframe.
- Added Doctype and updated meta tags
=> 8685bwuqw-embed-iframe-fix: Edit embed template to show in iframe

templates/projects/embed-project.html
Removed load static tag from HTML.
=> 8685bwuqw-embed-iframe-fix: removed load static tag

templates/partials/_update-account.html, templates/researchers/connect-researcher.html
Going to merge this right into develop so it can be tested, since testing it locally is not currently possible.
=> show orcid widget, update credentials and modify template

cloudbuild-dev.yaml, cloudbuild.yaml, helpers/management/commands/run_data_backup.py
feat: created possible fix for db backup dependency issue
=> 8685ck3u5-db-backup-dependency-fix

cloudbuild-dev.yaml, cloudbuild.yaml
Moves postgres client installation step before the deploy step.
=> feat: updated installing dependencies for pg_dump

helpers/management/commands/run_data_backup.py
Adds additional logging when successful
=> feat: added additional logging

cloudbuild-dev.yaml, cloudbuild.yaml
Extends the `python:3.8-slim-buster` image and installs postgres-client-15
=> feat: used prebuilt image with pg_dump 15

templates/partials/footers/_auth-footer.html
- Email template footer in MailGun: Updated icon sizes so they do not appear larger in some email providers.
- Added Vimeo to social media list in email footers and hub footer.
=> 8685ggtm7 updated social media icons in email and hub footer

accounts/views.py, templates/accounts/update-profile.html
**[Issue:](https://app.clickup.com/t/868733qnu)**
- Description: Update the error msg for the inactive user and add the username adjacent to user_id in the update-profile page
**Before:**
- Error msg for an `inactive user` or a `deactivated account`:
**After:**
- User Name adjacent to User ID:
=> 868733qnu Added username and updated error msg for unactive user

localcontexts/static/javascript/main.js, projects/views.py, templates/partials/_project-actions.html, templates/projects/embed-project.html
[Issue:](https://app.clickup.com/t/8685bwuqw)
- Allow users to embed any Labels and Notices associated with a Project by sharing from the Project page.
(Previous Issues for security and iframe loading: #24, #25, #50, #59, #63)
Workflow:
https://github.com/localcontexts/localcontextshub/assets/60452620/2aeb571d-5de2-4a5a-85d7-fdfaeeefe65a
=> #86871p6m2 Embed UI Updates

templates/accounts/login.html
**[Issue:](https://app.clickup.com/t/86877dv8a)**
- Before
- After
=> 86877dv8a Updated login page styling

templates/projects/embed-project.html
- Alignment fix for layouts 2 and 3
- standardize spacing for all layouts
- fixed notices src img link
- general condensing html
Before:
PR #71 
After:
=> 86875x1x8 Embed UI Updates

localcontexts/admin.py, researchers/utils.py, researchers/views.py
- Added if for HubActivity page if researcher is not available
- Updated is_researcher to pass None instead of False
=> #86878qevr hub activity page error

projects/urls.py
Fixed: Embed URL missing from Projects URLs leading to 404 error.
=> #8687a81bk Add embed url to staging

templates/403.html, templates/500.html, templates/accounts/confirm-account.html, templates/accounts/login.html, templates/accounts/newsletter-subscription.html, templates/communities/create-community.html
Altered in 403, 500, login, create community, confirm account, newsletter subscription.
Login
Before:
After:
Create Community 
Before:
After:
=> #86879gvx8 update css class for links

accounts/adapters.py, accounts/views.py, communities/views.py, institutions/views.py, localcontexts/static/css/main.css, researchers/views.py, templates/partials/_alerts.html
Adjusted CSS for all alerts and updated alert message content slightly for consistency.
Login Page
Before:
After:
**Note that this changes all alert messages to now take up the width of the container they're in. This might need to be adjusted in the future.**
Update profile page:
Invite member to institution or community:
=> #86879gz7v adjust alert messages

localcontexts/static/css/register.css, templates/communities/add-community-boundary.html, templates/communities/community-boundary.html, templates/communities/upload-boundary-file.html, templates/widget_forms/community/boundary_widget.html
This PR has a collection of content updates to improve the GIS UI.
To verify, you can confirm it meets the requirements of the Google Doc (not included)
=> #8685cga5j GIS Content Updates

helpers/views.py, templates/communities/upload-boundary-file.html, templates/widget_forms/community/boundary_widget.html
How to Verify First Bug Fix:
* Cause Bug on `develop` branch:
* visit this page. `http://localhost:8000/admin/communities/community/add/`
* observe error
* Checkout this branch:
* verify that visiting `http://localhost:8000/admin/communities/community/add/` does not cause an error
-------------
How to Verify Second Bug Fix:
* Cause Bug on `develop` branch:
* via command line, select a community
* set the boundary of community as None
* save community
* via the browser, visit `http://localhost:8000/helpers/community-boundary-view/<community-id-number>`
* observe error
* Checkout this branch:
* repeat steps above
* observe that error does not occur
=> #8686hvmd2 Admin Panel GIS bug fixes

localcontexts/static/css/dashboard.css, localcontexts/static/css/main.css, templates/partials/infocards/_community-card.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html, templates/snippets/notifications.html
This PR includes subtask [#8687a76ux](https://app.clickup.com/t/8687a76ux).
Problem: Inconsistencies in the UI for account cards, specifically buttons, in registry and profile pages.
Solution: Adjust CSS to make all buttons uniform in spacing.
**Before (Registry):**
**After (Registry):**
**Before (Profile):**
**After (Profile):**
=> #8687a73ua Account Cards UI adjustment

localcontexts/static/css/register.css, templates/accounts/select-account.html, templates/register-base.html
Updated general CSS for that page, changed the UI for the buttons, and added link to profile.
Select account page before:
Select account page after:
=> #8687dqb8y Select Accout UI update

templates/accounts/register.html
Video Demo
https://github.com/localcontexts/localcontextshub/assets/145378945/776e64a4-436f-4eb1-bcc6-d9962ebe2a8d
=> #86879qpjy: removed space from url

helpers/scheduler.py
- Updated the APS scheduler trigger condition, as it was facing issues with being triggered on the develop instance.
=> Updated scheduler trigger

.flake8, .github/workflows/run_testcases.yml, README.md, accounts/adapters.py, accounts/decorators.py, accounts/forms.py, accounts/models.py, accounts/signals.py, accounts/templatetags/custom_acct_tags.py, accounts/tests.py, accounts/urls.py, accounts/utils.py, accounts/views.py, pyproject.toml, requirements.txt, scripts/pre-commit.sh
In this code, only the `accounts` folder is being formatted (in the Git hook) and linted (in the Git hook and Pipeline).
During the pipeline, if any Python file (not being ignored) does not pass linting, then the pipeline fails.
Also, gradually, we will want to expand the scope of formatting and linting to all the other folders until all of the Python files (not being ignored) are being formatted and linted.
=> #8687um61k formatting and linting

institutions/urls.py, institutions/views.py, localcontexts/static/css/main.css, localcontexts/static/css/modals.css, localcontexts/static/javascript/main.js, projects/urls.py, researchers/urls.py, researchers/views.py, templates/accounts/embed-notice.html, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/projects/embed-project.html
Added ability to embed OTC Notice for Researcher and Institution accounts. (Note: UI may change for dropdown.)
Video showing embed process for Researcher account (same functionality for Institution accounts), disabled share button if no link added, and disabled share/download buttons for unconfirmed institution account.
https://github.com/localcontexts/localcontextshub/assets/60452620/a8e357a4-ce86-424a-a910-6d1d5f4c04ac
=> 86871pca1 OTC Notice embed

accounts/views.py, communities/views.py, helpers/utils.py, institutions/urls.py, institutions/views.py, localcontexts/static/css/main.css, localcontexts/static/css/modals.css, localcontexts/static/javascript/main.js, projects/urls.py, researchers/urls.py, researchers/views.py, templates/accounts/embed-notice.html, templates/partials/_notices.html, templates/partials/_project-actions.html, templates/projects/embed-project.html
The purpose of this PR is to keep subscriptions in sync with develop.This will:
* minimize merge conflicts once we merge the subscriptions branch into the develop branch
* prevent unwanted diffs from showing up in individual PR's to subscription
We will probably need a PR like this every couple days so that subscription doesn't fall too far behind
=> #8687dry0g update subscriptions branch

templates/partials/_update-account.html, templates/partials/_update-boundary-main-area.html
This creates content updates to the Community Settings Page
=> #8687u2pah gis content updates

helpers/utils.py, institutions/utils.py, institutions/views.py, templates/accounts/member-invitations.html
**[Issue:](https://app.clickup.com/t/8687zamdv)**
**Solution:**
- Detected the addition of members through the registry, registration process, and account dashboard and decreased the users_count if the role is admin or editor. 
- Detected the change in the role of any member and adjusted the users_count based on the role change.
- Detected the removal of the member from the institute and decreased the count if the removed member was an editor or admin.
- Disabled the new member invites for the institute when users_count is 0 if the role is editor or admin.
- Showed appropriate messages on every action performed by the user.
**After:**
The [link](https://drive.google.com/file/d/1jb1ZTnbDQVK3nkROrzRkqTCb6DGZgdml/view?usp=sharing) for the video
=> #8687zamdv users count functionality

accounts/views.py, helpers/utils.py, institutions/utils.py, institutions/views.py
This PR is to Add some code that got missed during rebasing.
=> Added missing code that lost during rebasing and merging

localcontexts/static/css/main.css, templates/accounts/embed-notice.html, templates/partials/_notices.html, templates/projects/embed-project.html
#133 Continued
- Added UI Updates for OTC Dropdown
- Issue [86884c9ff](https://app.clickup.com/t/6943000/86884c9ff): Fixed bug where clicking the link in the embed wouldn't load in browser properly
=> #86880bfct: OTC Notice Embed UI and Bug fix

localcontexts/static/javascript/main.js, templates/accounts/embed-notice.html, templates/projects/embed-project.html
Added JS function to open the hyperlink within the embed in a new tab.
=> #86884c9ff Hyperlink not opening in embeds when clicked

requirements.txt
This resolves [three security-related issues](https://github.com/localcontexts/localcontextshub/security/dependabot) discovered by dependabot.
=> Dependabot discovered vulnerability fix

institutions/views.py
**[Issue:](https://app.clickup.com/t/868893z1n)**
This error is related to notifying notified communities of any Project changes in develop . It looks like the crud_notices  helper function got a new argument has_changes   but this change is only reflected in researcher/views.py .  
It should also be reflected in institutions/views.py   and  communities/views.py   on both create_project   and edit_project   as well.
**Solution:**
- Update the function call with appropriate parameters
**Before:**
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/5600dfbe-9a5f-4fed-87a5-da99d85115c6
=> #868893z1n create project error

researchers/decorators.py, tests/unit/decorators/test_is_researcher.py
Before Changes:
https://github.com/localcontexts/localcontextshub/assets/145378945/1f22ad58-9132-4db2-9443-a0b86e590a07
-------------------------
After Changes
https://github.com/localcontexts/localcontextshub/assets/145378945/3252d08f-f7ce-49ce-baea-5a6e6bf0c3eb
=> #86887veg1 is_researcher decorator returns 404 when pk integer does not match an existing researcher

accounts/signals.py, helpers/logging.py, tests/unit/test_log_deleted_user.py
When a user is deleted, this code pretty prints useful debug information.
A testcase which verifies this functionality was also added.
=> #86881d703 account pre delete

localcontexts/static/css/dashboard.css, templates/institutions/connections.html
**[Issue:](https://app.clickup.com/t/8687ypjqe)**
**Solution:**
- Adjusted CSS for dashcard buttons
**After:**
=> #8687ypjqe Fixed UI of dashcard buttons on connections page

api/base/serializers.py
> [
{
"account_id": "4_i",
"users_count": 1,
"api_key_count": 10,
"project_count": 1,
"notification_count": 0,
"start_date": "2020-07-19T00:00:00Z",
"end_date": "2024-06-10T00:00:00Z",
"date_last_updated": "2024-05-10T11:31:09.067373Z"
},
{
"account_id": "45_r",
"users_count": 1,
"api_key_count": 10,
"project_count": 1,
"notification_count": 0,
"start_date": "2020-07-19T00:00:00Z",
"end_date": "2024-08-20T00:00:00Z",
"date_last_updated": "2024-05-10T12:48:24.995153Z"
}
]
=> #8688gb86g Updated the get end point to return account_id

helpers/views.py, templates/public.html, tests/factories/communities_factories.py, tests/functional/test_functional_example.py, tests/functional/test_public_boundary_view.py
Displays a community boundary (if it exists)
https://github.com/localcontexts/localcontextshub/assets/145378945/a31b9fa7-6b1c-4b5d-b9b9-aa5930e24447
=> #868885w2v Display Boundary to Public

accounts/forms.py, helpers/utils.py, institutions/forms.py, institutions/urls.py, institutions/utils.py, institutions/views.py, localcontexts/static/css/main.css, localcontexts/static/javascript/main.js, templates/accounts/confirm-subscription.html, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html
**[Issue:](https://app.clickup.com/t/8688bazhf)**
Description is attached in this [ticket](https://app.clickup.com/t/8688bazhf)
**Solution:**
- Updated ROR Institution creation form to add contact name and contact email.
-  Updated NoROR Institution creation form to add contact name and contact email.
- Updated the views to handle the submission of subscription of institute.
- Updated the templates to render the updated form fields 
- Updated the JS to add the clear form functionality to newly added fields
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/7d642afb-a1bb-436b-abd9-6c06c58a5e9c
=> #8688bazhf squash institution creation forms

accounts/forms.py, accounts/utils.py, researchers/urls.py, researchers/utils.py, researchers/views.py, templates/accounts/confirm-subscription.html, templates/researchers/connect-researcher.html
**[Issue:](https://app.clickup.com/t/8688bb00w)**
Description is attached in this [ticket](https://app.clickup.com/t/8688bb00w)
**Solution:**
- Updated the researcher creation form and added the subscription forms 
- Updated the connect-researcher template to add recaptcha
- Update the functions to make them general for both researcher and institute.
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/7a89b293-fba8-42c4-a603-02c1d709ac43
=> #8688bb00w Researcher account creation subscription form consolidation

templates/accounts/embed-notice.html, templates/projects/embed-project.html
Fixed link in embed being blocked when clicked. Now link opens in same tab.
=> #8688gv1hd Embed Link open in new tab bug

requirements.txt
Added vulnerability fix discovered by dependabot
=> Added vulnerability fix discovered by dependabot

helpers/utils.py, institutions/utils.py, institutions/views.py, localcontexts/static/javascript/main.js, researchers/views.py, templates/partials/_members.html, templates/partials/_project-actions.html, templates/projects/projects.html
**[Issue:](https://app.clickup.com/t/8688h668p)**
Handle the counts for accounts that has counts -1 and ensure that the count remains constant at -1.
**Solution:**
- Performed Check if the count is -1 then didn't update the count
- Handled Project count, Notification count, User Count, and API key count for institute accounts that has -1 stored in count
- Handled Project count and Notification count for the researcher accounts that has -1 stored in count
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/ac53946c-fea6-4c44-9843-617abf629fa6
=> #8688h668p account having count -1

institutions/views.py, localcontexts/static/javascript/main.js, templates/partials/_add-contributors.html, templates/partials/_add-projectperson.html
**[Issue:](https://app.clickup.com/t/8687xq7b5)**
The description of this PR is attached in this [Clickup-task](https://app.clickup.com/t/8687xq7b5) 
**Solution:**
- Resolved the issue of matching id of elements of multiple form
- Updated the rendering of already added project persons (contributors)
- Updated the deletion of already added project persons (contributors)
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/cd3b96df-5188-4dac-b898-93353838888e
=> #8687xq7b5 Bug: Project Person form duplication

api/base/serializers.py
=> #8688kfnrq updated subscription serializer to remove start and end date

accounts/forms.py, accounts/utils.py, helpers/emails.py, helpers/utils.py, institutions/utils.py, institutions/views.py, researchers/views.py, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html, templates/snippets/emails/internal/subscription-failed-info.html
**[Issue:](https://app.clickup.com/t/8688jg6vr)**
Right now, we still have the `is_submitted` functionality on the subscription forms during account creation process when the user that is creating the account does not have a first and/or last name.
In `create-profile` , we should make just the first name mandatory, then also include First Name and Last Name in the account creation form, where first name will also be mandatory but it should be also be pre-filled if it already exists.
This way, we don't have to have the  `is_submitted`  functionality because SF requires a name. 
Modify subscription inquiry type field per account type. 
- If account type is researcher, the inquiry type should only show Subscription, Something Else, Not Sure.
- If account type is institution, …
=> #8688jg6vr Adjustments on subscription workflow

api/base/views.py, api/versioned/v2/views.py
Updates the link to the Api's documentation.
=> #8687wb74m-update-documentation-link

institutions/forms.py, institutions/views.py, localcontexts/static/javascript/main.js, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html
**[Issue:](https://app.clickup.com/t/868746e8t)**
From @ar8117 via [Slack message](https://localcontexts.slack.com/archives/C05SU5R08R1/p1706042492.214079)
In prep for subscriptions (minor edit) this error message should be something along the lines of "This institution is already on the Hub to join that account click here." It should also be at the top of this section instead of having to scroll to the bottom (will add this to CU)
**Solution:**
- Updated ```main.js``` to remove the error 
- Updated the ```create-custom-institution.html``` and ```create-institution.html``` template to move the error message upwards
**Before:**
**After:**
=> #868746e8t Content Update

helpers/emails.py
Adjust welcome email to accommodate sandbox welcome email mailgun template
=> #8685dv1cq Adjust welcome email sending function

communities/views.py, institutions/views.py, researchers/views.py, templates/accounts/preparation.html
update views for prep step so that it shows up in the sandbox and update the prep step content for when it is viewed in the sandbox
=> #8688pqgz9-update-sandbox-prep-step

institutions/views.py, researchers/urls.py, researchers/views.py, templates/account-settings-base.html, templates/account_settings_pages/_api-keys.html
Added API Key manager to researcher settings. Same code base as #178 - institution only api key settings.
=> #8688gv3re: Researcher key settings

localcontexts/static/css/register.css, localcontexts/static/javascript/main.js
**[Issue:](https://app.clickup.com/t/8688tcw5n)**
From Ashley Rojas via Github [conversation](https://github.com/localcontexts/localcontextshub/pull/191#pullrequestreview-2086200180)  
one thing we may need to discuss is having an option at the top of the dropdown list that says something along the lines of name is not in this list so the dropdown can disappear and the typed in affiliation/org can be used.
**Solution:**
- Takes the User Input and pass it to showSuggestions() function
- If the User input doesn't match any relevantItems, the User input is shown top of list
- If the User input matches any relevantItems, the User input is replaced by that relevantItem
**After:**
https://github.com/localcontexts/localcontextshub/assets/145371882/c816081b-90b0-405a-85cb-eb88487c …
=> #8688tcw5n fix for suggestion box

requirements.txt
This updates urllib3 to 1.26.19
=> Resolves issue detected by dependabot

templates/snippets/emails/internal/community-application.html, templates/snippets/emails/internal/institution-application.html, templates/snippets/emails/internal/researcher-account-connection.html
This branch extends https://github.com/localcontexts/localcontextshub/pull/222 by adding the website emails to the email template.
These are the new commits:
* https://github.com/localcontexts/localcontextshub/commit/670d8fda3b8e469889971f0b67f5b2ba1fd71566
* https://github.com/localcontexts/localcontextshub/commit/17830bfaf9d3661022a6c4d63bf46ed54fe71b07
* https://github.com/localcontexts/localcontextshub/commit/696e2ebe1e235c730f0c2f2f21a498244d4d20c8
=> #8688t7y9g website in account creation email

api/forms.py, communities/urls.py, communities/views.py, institutions/views.py, localcontexts/settings.py, researchers/views.py, templates/account-settings-base.html, templates/account_settings_pages/_api-keys.html
Added API Key manager to community settings. Branching off of #216 - researcher api key settings added.
=> #8688gv6gb: Community key settings

communities/forms.py, institutions/forms.py, localcontexts/static/css/register.css, researchers/forms.py, templates/communities/create-community.html, templates/institutions/create-institution.html, templates/partials/_update-account-main-area.html, templates/researchers/connect-researcher.html, templates/snippets/emails/internal/community-application.html, templates/snippets/emails/internal/institution-application.html, templates/snippets/emails/internal/researcher-account-connection.html
**Community Account Creation:**
**Community Account Settings**
----
**Institution Account Creation:**
**Institutions Account Settings**
----
**Researcher Account Creation:**
-------------------------
-------------------------
=> #8688t7xjj account website field

requirements.txt
This updates a vulnerability discovered by dependabot
=> Updated djangorestframework to 3.15.2 to fix vulnerability

localcontexts/static/css/modals.css, templates/public.html
https://github.com/localcontexts/localcontextshub/assets/145378945/83be7b37-306b-463f-a5f3-64f581c95cc0
=> #8688xv3hn request to join modal bug fix

helpers/utils.py, institutions/utils.py, institutions/views.py, researchers/utils.py, researchers/views.py
While testing on SANDBOX there were some error while creating researcher account, and that was due to recent merge in subscription branch.
=> Added missing code from rebasing

templates/communities/add-community-boundary.html, templates/communities/upload-boundary-file.html
Add indication that this can be updated in settings after submission
-----
On Select NLD Boundary Page
----
On Upload Shapefile Page
=> #8688uh6ty add indication gis can be changed later

accounts/views.py, institutions/utils.py, localcontexts/static/javascript/main.js, templates/accounts/subscription-inquiry.html
**[Issue:](https://app.clickup.com/t/8688zhzra)**
- The Affiliations or Organizations dropdown should include:
- Community accounts in the Hub
- Institution (non-ROR) accounts in the Hub
- Service Provider accounts in the Hub (AR to add to SP branch when this is updated)
- Add an identifier to the dropdown list for the Type of account the name is associated with. For example:
- Wind Energy Institute of Canada
Nonprofit, Canada, Institution
- Non-ROR Institutions Name
Country Location (if provided by account), Institution
- Community Name
Country Location (if provided by account), Community
- Service Provider Name
Service Provider
- The "Not Found in ROR List" message could just be "Not in List".
**Solution:**
- Updated JS to update message to "Not in List"
- Passed …
=> #8688zhzra subscription inquiry suggestion box update

institutions/utils.py, institutions/views.py
**[Issue:](https://app.clickup.com/t/86891pef2)**
Based on last's dev team meeting: It was decided to rename the function add_user of institution.utils to avoid confusion with add_user_to_role of helpers.utils
**Solution:**
- Updated the name of function to `check_subscription_and_then_change_role`
=> #86891pef2 Rename add_user function 

.flake8, .style.yapf, pyproject.toml
This updates the maximum line length in the configs for the linter and formatter.
=> #868920zr1 update max line number

localcontexts/static/css/main.css, templates/partials/infocards/_community-card.html, templates/partials/infocards/_institution-card.html, templates/partials/infocards/_researcher-card.html
Account dashboard before:
User dashboard before:
Registry before:
<hr>
Account dashboard after:
User dashboard after:
Registry after:
=> UI quickfixes

templates/accounts/select-account.html
Images of the tooltips added below per account. May need some content updates @corrieroe. Can add to our working doc.
=> #8688k94fb Add tooltip to Select Account page

templates/boundary/show-remove-preexisting.html, templates/boundary/update-boundary-via-native-land-and-shapefile.html, templates/communities/update-boundary-via-native-land-and-shapefile.html, templates/communities/upload-boundary-file.html, templates/partials/_update-boundary-main-area.html
These changes add the ability to update a boundary name that was derived from a shapefile on the following pages:
* create community and upload shapefile page
* edit community boundary page 
* edit project boundary page
=> #8689039ch shapefile boundary name editable

accounts/views.py
This adjust the max number of items per registry page from 5 to 10
---
Before Change:
https://github.com/user-attachments/assets/e989ffaf-9a86-4058-8709-92f769536a84
----
After Change:
https://github.com/user-attachments/assets/ecb5f35f-3914-4c69-ae98-2b6db49080f1
=> #86891zv2x-increase-registry-page-count

tests/functional/test_create_community_gis_ui.py
This PR updates failing ui-testcases.
=> #86899y5nt-fix-failing-ui-testcases

serviceproviders/models.py, templates/partials/infocards/_service-provider-dashcard.html
Added the member count to the SP Dashcard. Connection counts coming after #277 is merged. Notices will be a count for the OTC Notice links
=> #86890zt6h Add member count to SP Dashcard

templates/communities/add-community-boundary.html
=> #8688uh6ty-update: Removes 75% width from div on Search NLD page

institutions/views.py, serviceproviders/urls.py, serviceproviders/views.py, templates/partials/_embed.html, templates/partials/_notices.html
Added the OTC Functionality for Service Providers. Removed whitespaces to match build reqs.
=> #8688taubu: Embed OTC Functionality added for SP

institutions/forms.py, templates/institutions/create-custom-institution.html
This adds the website field to the nonROR institution creation form
After update
=> #8688t7xjj-update: Adds the website field to the nonROR institution creation form

localcontexts/static/javascript/main.js
**[Issue:](https://app.clickup.com/t/8689afdjc)**
It was found in the develop branch that adding labels isn't working. The validation on the save label button wasn't working properly.
**Solution:**
- Updated validation in translationFormValidation function
- Updated the working of autocomplete function 
**Before:**
**After:**
https://github.com/user-attachments/assets/12d023cf-728e-49bf-91c4-74fc051979a2
=> #8689afdjc Unable to add translation of labels

templates/institutions/create-custom-institution.html
Here's what it looks like after
https://github.com/user-attachments/assets/c9180917-b0da-47b5-a990-5768ce16126c
=> #8689arv87 errors on custom institution creation form

accounts/views.py, localcontexts/static/css/main.css, templates/accounts/registry.html
Updated Filter on Registry
https://github.com/user-attachments/assets/f726881f-1141-488e-9dee-8bd4cfd1c2ca
=> #8688w5ehu: Registry UI Filter Update

templates/communities/connections.html, templates/institutions/connections.html, templates/researchers/connections.html
Buttons not aligned to right side of the card.
Before:
After:
=> #8689etctv: Researcher connections card UI fix

accounts/forms.py, researchers/views.py, serviceproviders/views.py, templates/institutions/create-custom-institution.html, templates/institutions/create-institution.html
**[Issue:](https://app.clickup.com/t/8689efbg1)**
The inquiry types have been updated on the SF side, which was causing errors during the SF calls.
**Solution:**
- Updated inquiry_types on the Subscription form
- Updated views of Researcher and Service Provider app
- Updated the templates for Institution creation and Custom Institution creation form 
**Before:**
https://github.com/user-attachments/assets/f5508326-7961-4243-a9e3-bf0a03b0baa7
**After:**
https://github.com/user-attachments/assets/0e7dafbd-07f4-4353-a7c3-4bd733803199
=> #8689efbg1 Subscription Inquiry_type update

helpers/emails.py, helpers/utils.py, serviceproviders/views.py
Added email send on SP account creation. Used current institution email template on account creation so content will need to be updated.
=> #8688w46yq: SP email on account creation

helpers/utils.py, templates/account_settings_pages/_community-boundary.html, templates/boundary/show-remove-preexisting.html, templates/boundary/update-boundary-via-native-land-and-shapefile.html, templates/communities/add-community-boundary.html, templates/communities/update-boundary-via-native-land-and-shapefile.html, templates/partials/_project-actions.html, templates/partials/_update-boundary-main-area.html
**Demo on the Edit Project Boundary Page:**
https://github.com/user-attachments/assets/ced03ccf-02e5-4197-8909-0f55c953955b
---------
**Demo on the Edit Community Boundary Page:**
https://github.com/user-attachments/assets/d2ea019a-3faf-41cd-b30d-1f27577cc5d1
=> #8689e4kkg name field additional changes

tests/factories/communities_factories.py
This uses unique values for the `community_name` test attribute:
https://faker.readthedocs.io/en/master/#unique-values
=> Use unique company name for tests

tests/unit/test_projects_models.py
This PR updates test_projects_models.py
=> #8689j65uj refactor test project models

communities/urls.py, communities/views.py, institutions/urls.py, institutions/views.py, localcontexts/static/css/main.css, localcontexts/static/css/register.css, researchers/urls.py, researchers/views.py, templates/account-settings-base.html, templates/account_settings_pages/_connect-service-provider.html, templates/account_settings_pages/_preferences.html
Added a preferences pages and moved the Show/Hide Account in SP registry from #303 to this preferences page.
https://github.com/user-attachments/assets/90b7c88f-cb43-42a1-b9c6-3d27a983be67
=> #8689hb8rt: Hub Account Preferences Page

projects/signals.py
**Issue:** 
- Any time an account creates a Project, it also creates a series of Project dependencies, one of them being `ProjectCreator`, which is linked to Project by account. When an account is deleted, it deletes the instance of `ProjectCreator` but NOT the Project its linked with. This causes orphaned Project instances that throw an error when viewed in the GUI.
**Solution:**
Created a signal to delete Project that was created by that account when an account is being deleted.
**Note:**
Accounts can only be deleted from admin at this time, so this will not cause any issues for users going through the GUI.
**How to test this:**
- Create a community, institution, or researcher account.
- Create a Project under that account.
- Go to admin, and delete the account.
- Go to admin/Projects …
=> #86878u8pn: Bug Fix: Project deletion on account deletion

api/base/serializers.py, api/base/views.py
https://github.com/user-attachments/assets/f45ad71e-cbed-4b1a-8ac1-9f684d58ffb8
=> #8689q6g1d: Add DOI and GUID as search params and fields in API v1

templates/partials/_project-actions.html, tests/functional/test_preview_boundary_ui.py
This PR has testcases which verify that cleared boundaries aren't accidentally saved.
=> #8689u4y60 fix boundary saved after cleared testcases

templates/partials/_notices.html
=> #8689wb7pf CC Notice content update

communities/models.py, communities/views.py, institutions/models.py, institutions/views.py, localcontexts/static/css/dashboard.css, researchers/models.py, researchers/views.py, serviceproviders/views.py, templates/account_settings_pages/_api-keys.html, templates/account_settings_pages/_connect-service-provider.html, templates/public.html
Misc Bug Fixes:
- #868a2xg0x: Bug fix, API key count not showing in user settings
- #868a2xgvv: Bug fix: 404 error when saving preferences settings
- #8689un1zg: Bug fix SP registry card height
Misc UI updates:
- #8689un2kg: More info button icon changed to external link indicator
- #8689q236z: Website link added for all account cards in registry page
- #8688hmwdm: Filtered out revoked or expired API Keys from showing in user settings
=> Misc SP bug updates

tests/functional/test_cleared_boundaries_are_not_saved_ui.py, tests/functional/test_preview_boundary_ui.py
This disables the NLD update until our HUB update is complete
=> Disabled nld testcases

accounts/views.py, institutions/views.py, templates/account_settings_pages/_connect-service-provider.html, templates/accounts/select-account.html, tests/functional/test_cleared_boundaries_are_not_saved_ui.py, tests/functional/test_preview_boundary_ui.py
=> #868a57jg1: Added Sandbox blocks to SP functionality
